 #!/usr/bin/python
"""
MESMER -- MEmoryze String MappER

This script is used to search the av.db file generated by Memoryze by Mandiant.
#ProTip: Ensure you enumerate strings in memory when you run Memoryze for best results.

This script requires two arguments:
    The path to the av.db file.
    The string you are searching for (the search is NOT case sensitive).

usage example:
    python mesmer.py -f C:\audit\av.db -s "evil string"
"""


from optparse import OptionParser
import sqlite3
import sys
import os

def searchDB(filepath, searchstring):
  con = None
  
  try:
    con = sqlite3.connect(filepath)

    #find all the 'strings' tables.
    cur = con.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'strings_%'")

    #put the table names into a list
    tables = []
    tables = cur.fetchall()

    # loop through each table search for that string.
    for table in tables:
      cur.execute("SELECT pid, string FROM " + table[0] + " WHERE string LIKE '%" + searchstring + "%'")
      rows = cur.fetchall()
      
      #do work on only results found
      if len(rows) > 0:

        # db search for process information
        pid = str(rows[0][0]) # use the first result from the search above for sourcing the pid
        cur.execute("SELECT pid, parentpid, name, starttime, arguments, username, securityid, path, score FROM processes WHERE pid  = '" + pid + "'")
        process = cur.fetchall()

        #display the process
        print "======================================"
        print "PID:", process[0][0]
        print "Parent PID:", process[0][0]
        print "Process Name:", process[0][2]
        print "Start Time:", process[0][3]
        print "Arguments:", process[0][4]
        print "Username:", process[0][5]
        print "Security ID:", process[0][6]
        print "Path:", process[0][7]
        print "Score:", process[0][8]
        print "======================================"
          
        #display the pid and the whole string it found
        for row in rows:
          print str(row[0]) + " -- " + row[1]
    
  except sqlite3.Error, e:
    print "Error %s" % e.args[0]
    sys.exit(1)

  finally:
    if con:
      con.close()


def main():
  parser = OptionParser(usage="usage: %prog [options]",
                        version="%prog 1.0")
  parser.add_option("-f",
                    action="store",
                    dest="filepath",
                    default=False,
                    help="This is the path to av.db file that Memoryze creates.")
  parser.add_option("-s",
                    action="store",
                    dest="searchstring",
                    default=False,
                    help="The string you want to search the file for, use double quotes \" \".",)
  (options, args) = parser.parse_args()

  # check to make sure all arguments are present
  mandatory = ['filepath', 'searchstring']
  for m in mandatory:
    if not options.__dict__[m]:
      print "Mandatory argument is missing.\n"
      parser.print_help()
      sys.exit(1)

  # run the search
  searchDB(options.filepath, options.searchstring)


if __name__ == '__main__':
    main()